# Generated by Django 5.2.16 on 2026-07-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UMS', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['-date_joined'], name='ums_user_date_joined_idx'),
        ),
    ]
