# Generated by Django 6.0.5 on 2026-06-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CategoryProductMazaneh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_mazaneh', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True, verbose_name='مظنه خرید')),
                ('sell_mazaneh', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True, verbose_name='مظنه فروش')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تأیید شده'), ('rejected', 'رد شده')], default='pending', max_length=10)),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('trade_type', models.CharField(blank=True, choices=[('buy', 'خرید'), ('sell', 'فروش')], default='buy', max_length=10, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('can_buy_online', models.BooleanField(default=True, verbose_name='امکان خرید آنلاین توسط کاربر')),
                ('can_sell_online', models.BooleanField(default=True, verbose_name='امکان فروش آنلاین توسط کاربر')),
                ('endpoint', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
    ]
