# Generated by Django 6.0.5 on 2026-06-07 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('OMS', '0001_initial'),
        ('UMS', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryproductmazaneh',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_mazaneh', to='UMS.usercategory'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='OMS.product'),
        ),
        migrations.AddField(
            model_name='categoryproductmazaneh',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_mazaneh', to='OMS.product'),
        ),
        migrations.AddField(
            model_name='baseprice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_prices', to='OMS.product'),
        ),
        migrations.AlterUniqueTogether(
            name='categoryproductmazaneh',
            unique_together={('category', 'product')},
        ),
    ]
