# Generated by Django 6.0.5 on 2026-06-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMS', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='endpoint',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
