# Generated by Django 6.0.5 on 2026-06-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMS', '0003_alter_product_endpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='endpoint',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(choices=[('سکه امامی تک فروشی', 'سکه امامی تک فروشی'), ('سکه بهار آزادی تک فروشی', 'سکه بهار آزادی تک فروشی'), ('نیم سکه تک فروشی', 'نیم سکه تک فروشی'), ('ربع سکه تک فروشی', 'ربع سکه تک فروشی'), ('سکه گرمی تک فروشی', 'سکه گرمی تک فروشی'), ('ربع سکه', 'ربع سکه'), ('سکه امامی', 'سکه امامی'), ('سکه بهار آزادی', 'سکه بهار آزادی'), ('نیم سکه', 'نیم سکه'), ('سکه گرمی', 'سکه گرمی'), ('طلا 18 عیار', 'طلا 18 عیار'), ('گرم نقره 999', 'گرم نقره 999'), ('مثقال طلا', 'مثقال طلا'), ('آب شده معاملاتی', 'آب شده معاملاتی'), ('آب شده نقدی', 'آب شده نقدی'), ('مثقال بدون حباب', 'مثقال بدون حباب')], max_length=255),
        ),
    ]
