# Generated by Django 6.0.5 on 2026-07-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMS', '0004_alter_product_endpoint_alter_product_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseprice',
            name='zaryar_buy_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='قیمت خرید زریار'),
        ),
        migrations.AddField(
            model_name='baseprice',
            name='zaryar_sell_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='قیمت فروش زریار'),
        ),
        migrations.AddField(
            model_name='product',
            name='zaryar_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='شناسه محصول در زریار'),
        ),
        migrations.AddField(
            model_name='product',
            name='zaryar_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان محصول در زریار'),
        ),
    ]
