# Generated by Django 6.0.5 on 2026-07-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMS', '0006_alter_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseprice',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True),
        ),
    ]
