# Generated by Django 6.0.5 on 2026-07-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMS', '0007_alter_baseprice_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='zaryar_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='شناسه محصول در زریار'),
        ),
    ]
