# Generated by Django 6.0.5 on 2026-07-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMS', '0008_alter_product_zaryar_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='endpoint',
        ),
        migrations.AlterField(
            model_name='categoryproductmazaneh',
            name='buy_mazaneh',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='مظنه خرید'),
        ),
        migrations.AlterField(
            model_name='categoryproductmazaneh',
            name='sell_mazaneh',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='مظنه فروش'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='zaryar_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='شناسه محصول در زریار'),
        ),
    ]
