# Generated by Django 5.2.16 on 2026-07-30 09:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMS', '0010_delete_productcategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='baseprice',
            index=models.Index(fields=['product', '-created_at'], name='oms_bp_product_created_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-created_at'], name='oms_order_created_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-created_at'], name='oms_order_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='oms_order_status_cr_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['product', '-created_at'], name='oms_order_product_cr_idx'),
        ),
    ]
